### PR TITLE
Add news on Bannan webinar

### PR DESCRIPTION
**Pull request by davidlmobley**
Adds news entry mentioning Bannan webinar this week. @leeping please review and merge if it looks OK.

### CODE REVIEW

**Comment by leeping** [comment]
I don't think I have merge privileges.

**Comment by davidlmobley** [comment]
Oops. OK, I'll merge, but I'll fix that.

**Comment by davidlmobley** [comment]
Fixed, @leeping

**Comment by leeping** [comment]
Thanks a lot. :)

**Pull request merged**
