### PR TITLE
Add missing papers

### PR DESCRIPTION
**Pull request by jchodera**
This PR adds all recent OpenFF papers (funded by the Initiative or Consortium) that have not yet made it up onto the website.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Hm, other things I'd missed that may belong here/may not be here yet:
- Setiadi "tuning to host-guest binding" preprint which acknowledges the grant: https://chemrxiv.org/engage/chemrxiv/article-details/650e17d060c37f4f7645e921
- Hahn benchmarking preprint: https://chemrxiv.org/engage/chemrxiv/article-details/64e86ea479853bbd7862b98a (but not NIH funded)
- Chapin Cavender experimental data preprint (but may have been cited in last proposal?): https://arxiv.org/abs/2303.11056
- Simulations of protein crystals (which can test force fields); I'd acknowledged the grant because of MY effort on the project, and it relates: https://onlinelibrary.wiley.com/iucr/doi/10.1107/S2059798322011871
- Looks like qcdb paper you co-authored acknowledges this grant: https://pubs.aip.org/aip/jcp/article/155/20/204801/280526/Quantum-Chemistry-Common-Driver-and-Databases-QCDB

I am not seeing anything else offhand but that doesn't prove we didn't miss something. Pretty sure this is adequate for now; anything else acknowledging the grant should eventually get linked via its reference to the grant even if we don't reference it in the proposal.

**Comment by davidlmobley** [comment]
- Ken Takaba preprint? https://arxiv.org/pdf/2307.07085.pdf
- SPICE dataset? https://pubmed.ncbi.nlm.nih.gov/36599873/

**Comment by davidlmobley** [comment]
Tobias crystal modeling work now up on Zenodo and citeable, as of approximately now: https://zenodo.org/records/10038276

**Comment by jchodera** [comment]
Thanks so much, @davidlmobley!

I'm going to punt on the talk, since we don't have a category for that yet. I'll open an issue to add that later:
https://github.com/openforcefield/openforcefield.org/issues/476

**Pull request merged**
