### PR TITLE
Add openff-1.3.1 to force fields page

### PR DESCRIPTION
**Pull request by j-wags**

### CODE REVIEW

**Comment by j-wags** [comment]
@karmencj Could you review + merge if this looks good? Thanks!

**Comment by jchodera** [comment]
@karmencj : It doesn't look like this deployed:
https://openforcefield.org/force-fields/force-fields/
image

**Comment by j-wags** [comment]
Ah, this was still on travis.ORG instead of .COM. It seems travis.ORG shut down operations in the last few days. Ultimately we'll want to move this to GitHub actions, but I'm going to try quickly migrating to travis.COM quickly to see if that resolves it.

**Comment by karmencj** [comment]
I checked an hour ago and also noticed that it didn't deploy, but didn't have time to look into it. Thanks @j-wags for checking it!

**Comment by j-wags** [comment]
Darn. No luck. I think the next step is to move to GitHub Actions. I'll give this a shot tomorrow. The joys of the free tier :-P

**Comment by j-wags** [comment]
Ah, did some more searching this morning and fixed it on travis.COM. Root cause was that, after migrating to travis-ci.COM, there was no plan selected, so I had to select the "free" option to proceed. https://github.com/travis-ci/docs-travis-ci-com/issues/733#issuecomment-858785406

**Comment by jchodera** [comment]
The text says:
"The new force field files in this release are identical to the openff-1.3.0 release, except that two angle parameters have been reverted to their original values from smirnoff99Frosst 1.1.0."

Since this is supposed to be the brief informative version, what about being less vague and making it clearer why this bugfix was needed?

"This release is a bugfix for openff-1.3.0 that corrects an issue with the tetrahedral geometry of certain sulphonamides (especially primary sulphonamides)."

That's probably going to be much more useful to folks than the mysterious "two angle parameters" comment.

**Comment by j-wags** [comment]
Good call. Updated in 4d23c6efe82d9e7b6f4699b586e18b899c57be1f

**Pull request merged**
