### PR TITLE
Add Jeff Wagner

### PR DESCRIPTION
**Pull request by davidlmobley**
Adds page for @j-wags

Jeff, if you have twitter, a Google Scholar profile, a website, etc., feel free to update with that info.

### CODE REVIEW

**Comment by jchodera** [comment]
Don't forget you have to rebuild the website by running `hugo` in `openforcefield/` in order to have this update the static website once merged.

**Comment by davidlmobley** [comment]
You're right, I forgot that this time. Still getting used to it. :)

**Comment by j-wags** [comment]
Done. Thanks, John and David.

**Comment by j-wags** [comment]
Ahh -- I see how this works. My mistake. Working on it now. Will submit PR shortly.

**Pull request merged**
