### PR TITLE
Update some links

### PR DESCRIPTION
**Pull request by mattwthompson**
Updated the evaluator links to point to its new name and added some doc links for repos that did not previously have docs hosted on RTD. The RTD links are still broken in the [rendered markdown](https://github.com/openforcefield/openforcefield.org/blob/update-urls/content/consortium/software/_index.md) at the time of opening this PR, not sure if RTD needs to make those badges on their end or something; I think the links are the same as the other projects with pretty badges

### CODE REVIEW

**Comment by mattwthompson** [comment]
@karmencj I think everything here is fixed now (see [here](https://github.com/openforcefield/openforcefield.org/blob/update-urls/content/consortium/software/_index.md)). However, if this is going to get replaced entirely with a website update and it doesn't make sense to fix now, please feel free to close

**Review by j-wags — APPROVED** [review]
LGTM. Thanks, Matt!

**Comment by mattwthompson** [comment]
On second thought, I have also updated the travis badges to GHA badges. It's misleading that, for example, the OFFTK badge is red when it's just the last test (almost a month ago) that happened to fail.

**Comment by j-wags** [comment]
Sounds good. Merge whenever you're ready!

**Comment by mattwthompson** [comment]
The same file thrown to gist was giving some issues, although the files here in the actual repo look fine. So I'll go ahead and merge. Thanks for the quick review (well, after I left it to sit for 2 weeks 😅)

**Pull request merged**
