### PR TITLE
Update travis hugo building

### PR DESCRIPTION
**Pull request by j-wags**
Bit of a shot in the dark. I don't understand much about Go module handling, but this showed up in a google search.

https://github.com/jdkato/prose/issues/57#issuecomment-647855442

### CODE REVIEW

**Comment by j-wags** [comment]
I've switched in the hugo install method from [their docs](https://gohugo.io/getting-started/installing/) (starting with a `git clone`)

Builds seem to have stopped explicitly failing, though I'd like a way to verify that they are actually working. I'm going to think about how to do this.

**Comment by j-wags** [comment]
Builds go suspiciously fast now, and produce smaller numbers of pages. I am wary.

A build that worked a few weeks ago: https://travis-ci.org/github/openforcefield/openforcefield.org/builds/697066198#L223-L234
```
                   | EN   
-------------------+------
  Pages            | 412  
  Paginator pages  | 107  
  Non-page files   | 131  
  Static files     |  46  
  Processed images |   0  
  Aliases          | 162  
  Sitemaps         |   1  
  Cleaned          |   0  
Total in 607 ms
```
A build from this PR: https://travis-ci.org/github/openforcefield/openforcefield.org/builds/702548302#L448-L459
```
                  | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0 
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  
Total in 19 ms
```

**Comment by jchodera** [comment]
@j-wags If you're having trouble with the builds, why not use the `hugo` version from a stable release, like this one?
https://github.com/gohugoio/hugo/releases/tag/v0.72.0

I think we can just use [go modules support](https://github.com/golang/go/wiki/Modules) to enable checking out a specific tag:
```bash
go mod init .
go get github.com/gohugoio/hugo@v0.72.0
```

**Comment by j-wags** [comment]
Good call. Trying that now.

**Comment by j-wags** [comment]
Huzzah! The env variable approach seems to have done it. Merging!
https://travis-ci.org/github/openforcefield/openforcefield.org/builds/703649482#L310-L321
```
-------------------+------
  Pages            | 412  
  Paginator pages  | 107  
  Non-page files   | 131  
  Static files     |  46  
  Processed images |   0  
  Aliases          | 162  
  Sitemaps         |   1  
  Cleaned          |   0  
Total in 575 ms
```

**Pull request merged**
