### PR TITLE
Update description for the learned chemical perception paper

### PR DESCRIPTION
**Pull request by bannanc**
On Monday we realized the learned chemical perception paper had the same description as the SMIRNOFF paper. I've added a new description for the learned chemical perception paper.

### CODE REVIEW

**Comment by leeping** [comment]
Thanks, Caitlin. Can you please build the site and push a new commit? (It's described at the bottom of the readme.)

**Comment by bannanc** [comment]
@leeping 
I followed the instructions on the README, except for the last step:
`3. Commit the changes and push the repository to master`
Because I assume that is what I'm doing in the pull request. However, there weren't any changes to push when I finished the deploy part. 

Just to be specific, this is what I did:
1. `brew install hugo`
2. in the openforcefield folder I ran `hugo server -D`
3. checked the local host site, changes look good, so Ctrl+C to leave that
4. in the top directory `cp CNAME docs/` 
5. `git add docs/*` and `git commit -m "building website"`
6. `git push origin smarty` which returned `Everything up-to-date`

**Comment by bannanc** [comment]
Also, this has a green merge button for me, you may want to set the protections to be a bit stricter so that only administrators can merge, or at least that a review has to pass first.

**Comment by leeping** [comment]
> Just to be specific, this is what I did:
> 
> 1. `brew install hugo`
> 2. in the openforcefield folder I ran `hugo server -D`
> 3. checked the local host site, changes look good, so Ctrl+C to leave that

Thanks for the clarifications. I think possibly the missing step after step 3 is you need to run `hugo` without any arguments in the same folder where you ran `hugo server -D`.  This generates the needed changes in `docs` that you need to include in the commit.

Thanks,

- Lee-Ping

PS: Though I haven't heard from @davidlmobley and @jchodera , I think perhaps we are intentionally being lenient with the permissions while encouraging everyone to request reviews when appropriate.  I know that sounds vague but I think it may work better than having only a few people "hold the keys" so to speak.

**Comment by davidlmobley** [comment]
Built and pushed; added .gitignore template to ignore some OS X files too. 

Permissions: I'd given Caitlin write privileges and we haven't locked out merging for people with write privileges. We could.

**Pull request merged**
