### PR TITLE
Add Jan 2019 minutes from Open Force Field Consortium Advisory Board meeting

### PR DESCRIPTION
**Pull request by jchodera**
I've formatted the meeting minutes from Arjun Narayanan.

### CODE REVIEW

**Comment by leeping** [comment]
There currently isn't a link under `consortium/` which is where we have had our previous meeting minutes.  Could you please move it over?

**Comment by jchodera** [comment]
Oh! I had totally missed that. Will move.

**Comment by jchodera** [comment]
I've moved the minutes and cleaned up the summaries.
image
Thanks for pointing this out!

**Comment by leeping** [comment]
Thanks, looks great now. :)

**Pull request merged**
