### PR TITLE
Make Software page public

### PR DESCRIPTION
**Pull request by j-wags**
I also changed the "Code" link in the header to redirect to this page instead of the OFF toolkit repo.

We may want to change the wording/formatting at the top of the code page. @jchodera and @karmencj , feel free to unilaterally make edits. 

Screen Shot 2019-08-06 at 10 42 45 AM
Screen Shot 2019-08-06 at 10 42 57 AM
Screen Shot 2019-08-06 at 10 43 11 AM

### CODE REVIEW

**Comment by j-wags** [comment]
Per discussion with @karmencj, we should add a figure and descriptions of each component to this page before it goes live.

**Comment by jchodera** [comment]
I think we want two separate pages: One meant for developers (this page), and one meant for users (focusing on quick-read descriptions, documentation, and installation badges). The information on the first page is really meant for us to make sure everything is healthy.

**Comment by jchodera** [comment]
@j-wags : Would it be OK if we revive this page before the website overhaul? I think it would be super useful, and I'd hate to lose it!

**Comment by j-wags** [comment]
Yes. I'm OK to merge this as-is. I won't have time to work on a more complete "Description" page in the near future, so it's probably best to just merge this before we forget again. Could you approve the PR + merge if you're OK with the current status @jchodera ?

**Pull request merged**
