### PR TITLE
Small updates to bespoke blog post

### PR DESCRIPTION
**Pull request by j-wags**
Added env yaml and updated code snippets per https://github.com/openforcefield/bespoke-fit/issues/79

### CODE REVIEW

**Comment by j-wags** [comment]
I'm going to merge this now since the weekend is coming up. @Yoshanuikabundi, when you start work next week, could you check you're able to run the example by following the instructions in the blog post?

**Comment by Yoshanuikabundi** [comment]
@jthorton  @j-wags Everything works great except right at the end I can't view the PDF with the graph comparing the output and input. The folder (with the big alphanumerical name) inside the `bespoke-executor` directory is deleted during the optimization step. I can confirm that the folder is created, and using the `executor.start()` method rather than the context manager doesn't fix it. Might be a Linux thing? Looks like I can still get all the results out of the `result` object.

**Comment by jthorton** [comment]
@Yoshanuikabundi Thanks for testing this out. I think the cleanup part might be due to the version of bespokefit in the env file I think this might need changing to `c087e0e`.

**Comment by Yoshanuikabundi** [comment]
@jthorton Tried just pip installing that commit over the top of the environment. Had to change `parameters = schema.parameters` to `parameters = schema.stages[0].parameters` in a previous cell and then got a 
`RuntimeError: The gateway could not be reached.` when I tried to do the executor, which I was not getting previously. Will try with a clean environment tomorrow in case that's the problem.

**Comment by jthorton** [comment]
@Yoshanuikabundi Ahh sorry that commit had an API breaking change where we introduce multi-stage fitting. Ill test locally to confirm the correct commit for the blog post.

**Comment by jthorton** [comment]
@Yoshanuikabundi I was able to run the notebook using commit  `931bb66bb3700208616e41bfde1a80d90a37d74f`. Looks like I might need to update the notebook once we finish this next update.

**Pull request merged**
