### PR TITLE
Updated Jeff Wagner's profile with Google Scholar/orcid/linkedin

### PR DESCRIPTION
**Pull request by j-wags**
Added links to my personal pages. I don't have a twitter/other public platform, but I keep my Google Scholar and Linkedin current (and I plan to get my ORCID up to speed eventually, too)

### CODE REVIEW

**Comment by j-wags** [comment]
Yes -- Maybe it should be a category for OpenFF full-timers in general, since we'll be the primary contact points. Are there any other full-timers currently? I think David said that some others would be coming online in the next few months.

Depending on what the other full-timers' roles will be, the category could be "Software Scientists", "Scientific Staff", "Full-Time Staff" or something encompassing like that.

**Comment by davidlmobley** [comment]
Definitely we should get @dgasmith up. Provide a photo, Daniel?

The issue @j-wags raises of distinguishing "effort level" of people could be worth doing but it may also be confusing or too hard to do. Many of the people listed are (or will be) full time on this. Or maybe he is getting at more the idea of "staff" vs "students and postdocs".

**Comment by jchodera** [comment]
It may not be difficult to add an effort level to the YAML files. This could be very helpful for automated dumps of reports for grants, etc.

**Comment by davidlmobley** [comment]
@leeping -- see thought about "effort level" in YAML. If you think it's a good idea we should create an issue.

**Comment by leeping** [comment]
I don't think this is a great idea (at least for public display), though I'm aware of the benefits.  I would prefer to mention specific cases in the "description" if needed.

**Comment by jchodera** [comment]
We will eventually want to capture all funding sources and effort on each funding source for purposes of generating internal reports for grants, etc.

**Comment by jchodera** [comment]
Also, it's worthwhile to be transparent in our funding sources for this project. We can figure out how to do this in an unobtrusive manner eventually.

**Comment by leeping** [comment]
I fully agree regarding the benefits. I'd be okay with having fields in the YAML for this purpose, which would make this info publicly available, but it's too complicated to think about how to display it on the website (and how people would interpret them). For example, none of us are getting summer salary, but if we report 0% effort level, that would raise a lot of eyebrows.

**Comment by jchodera** [comment]
I think it would be sufficient to have something like:
> Funding: [[NIH]](https://projectreporter.nih.gov/project_info_description.cfm?aid=9564960&icde=41542422&ddparam=&ddvalue=&ddsub=&cr=2&csb=default&cs=ASC&pball=) [[NSF]](https://nsf.gov/awardsearch/showAward?AWD_ID=1738979&HistoricalAwards=false) [[Consortium]](http://openforcefield.org/consortium) [[MolSSI Phase I Fellowship]](https://molssi.org/2018-phase-i-molssi-software-fellows/)

or some subset of those. That doesn't report percent effort, but does fulfill our obligations with respect to reporting potential financial conflicts of interest by listing all sources of funding.

**Comment by leeping** [comment]
I agree that’s a good idea, perhaps also include award numbers for the government grants.

**Comment by jchodera** [comment]
The links go to the award numbers, but you're right, we could print them too.

Would something like this work?
```YAML
--- 
funding: 
  - 
    award_number: "R01 GM121505"
    effort: 25%
    end_date: 2019-01-01
    source: NIH
    start_date: 2018-01-01
    url: "https://projectreporter.nih.gov/project_info_description.cfm?aid=9564960&icde=41542422&ddparam=&ddvalue=&ddsub=&cr=2&csb=default&cs=ASC&pball="
  - 
    award_number: 1738979
    effort: 25%
    end_date: 2019-01-01
    source: NSF
    start_date: 2018-01-01
    url: "https://nsf.gov/awardsearch/showAward?AWD_ID=1738979&HistoricalAwards=false"
```
We probably can have a separate `funding.yaml` that has the URL indexed by grant number so we don't need to look it up every time. `start_date`, `end_date`, and `effort` are for the individual applied to the grant, not the grant dates.

**Comment by leeping** [comment]
That works for me. I'll do this in a separate PR, but need to lecture very soon.

**Pull request merged**
