### PR TITLE
Update Matt's headshot

### PR DESCRIPTION
**Pull request by mattwthompson**
\*checks watch\* It's not 2018 anymore

### CODE REVIEW

**Comment by mattwthompson** [comment]
I can't build this locally

```
$ hugo server -D                                                                          9:04:35  ☁  new-matt-headshot ☀

Watching for changes in /Users/mattthompson/software/openforcefield.org/{archetypes,content,data,static,themes}
Watching for config changes in /Users/mattthompson/software/openforcefield.org/config.toml
Start building sites …
hugo v0.126.1+extended darwin/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=brew

Built in 57 ms
Error: error building site: assemble: failed to resolve media type for "mmark"

**Review by j-wags — APPROVED** [review]
Local build failures aside, this works on my machine (TM). The scale of the current shot is a bit close-in so your face is basically consuming the whole little circle (I tried to add a buffer around the original photo, but the the way the circle crop works made it look bad). Feel free to merge as-is or retake it. 

Screenshot 2024-05-20 at 12 15 51 PM

**Comment by mattwthompson** [comment]
well I don't like that

I'll grab another photo soon and merge if the silicon gods so allow me to built a website locally

**Comment by mattwthompson** [comment]
Okay, I found out why I couldn't build it locally. The website doesn't build with newer versions of `hugo` and it's pinned to an old version in the setup: https://github.com/openforcefield/openforcefield.org/blob/44186315d6d821c49be6e23acab2a2428f895494/.github/workflows/hugo.yml#L37

With a fairly hacky process: https://discourse.gohugo.io/t/switching-hugo-versions/38251/2


I can install this version and built it locally and look roughly as zoomed-in as my peers: 
image

**Pull request merged**
